"""Add ai_updated_at and admin_updated_at to Prediction table

Revision ID: 908c1ea21fda
Revises: 5fd11cdf6916
Create Date: 2025-04-22 20:38:57.759567

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '908c1ea21fda'
down_revision = '5fd11cdf6916'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('prediction', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ai_updated_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('admin_updated_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('prediction', schema=None) as batch_op:
        batch_op.drop_column('admin_updated_at')
        batch_op.drop_column('ai_updated_at')

    # ### end Alembic commands ###
